# Generated by Django 3.1.6 on 2021-03-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210316_0434'),
        ('seller', '0002_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
    ]
